// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCFo1LiyhwX-yFJ1t1xJpTsvmcVsECu84',
    appId: '1:855120160452:web:ae81b335bb47649af74b91',
    messagingSenderId: '855120160452',
    projectId: 'siniops',
    authDomain: 'siniops.firebaseapp.com',
    storageBucket: 'siniops.firebasestorage.app',
    measurementId: 'G-HZ0GYZDDPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuSzl5tcUhPImnqUDjWItlbli6m9qk_5I',
    appId: '1:855120160452:android:5f41bfcc9d76dfebf74b91',
    messagingSenderId: '855120160452',
    projectId: 'siniops',
    storageBucket: 'siniops.firebasestorage.app',
  );
}
